services:
  db:
    image: postgres:16-alpine
    container_name: taskflow_db
    environment:
      POSTGRES_DB: ${DB_NAME:-taskflow_db}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - taskflow_pgdata:/var/lib/postgresql/data # volume para persistencia de dados
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME:-taskflow_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: taskflow_api
    image: img_taskflow_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-taskflow_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_VITE: ${FRONTEND_URL_VITE}
    depends_on:
      db:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: taskflow_keycloak
    command: start-dev --import-realm # importa o realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Por enquanto, rodar no modo dev (banco H2 interno).
      # No futuro, para produção, apontar o KC_DB para o Postgres.
    ports:
      - "9090:8080" # Expõe o Keycloak na porta 9090
    # localização do realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - db

volumes:
  taskflow_pgdata: