spring.application.name=api-taskflow

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET}

cors.allowed.origins=${FRONTEND_URL:http://localhost}, ${FRONTEND_URL_VITE:http://localhost:5173}