spring.application.name=api-taskflow

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

api.security.token.secret=${JWT_SECRET}

api.cors.frontend.url=${FRONTEND_URL:http://localhost}
api.cors.frontend.url.vite=${FRONTEND_URL_VITE:http://localhost:5173}