spring.application.name=api-taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflowdb
spring.datasource.username=postgres
spring.datasource.password=1919
spring.docker.compose.enabled=false